# Generated by Django 6.0.1 on 2026-02-04 05:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent_id', 'id']},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='healthapp.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'title')},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.CreateModel(
            name='RadarChartData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radar_values', to='healthapp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radar_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'radar_chart_data',
                'ordering': ['user_id', 'category_id'],
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='RadarChart',
        ),
    ]
