# Generated by Django 5.2.7 on 2026-02-05 02:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_lifestyle_self_evaluation_alter_lifestyle_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealTimeAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ideal_hours', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_time_allocations', to='healthapp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_time_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ideal_time_allocation',
                'ordering': ['user_id', 'category_id'],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
